name = "gimlight"
version = "0.1.0"
defaultTargets = ["gimlight"]

[[require]]
name = "loop"
path = "./packages/loop"

[[require]]
name = "terminal"
path = "./packages/terminal"

[[lean_lib]]
name = "Gimlight"
roots = ["Gimlight"]
globs = []

[[lean_exe]]
name = "gimlight"
root = "Main"
