resolver: lts-22.15

packages:
  - bin
  - logic

# As most of packages are inferred as `unsafe`, building with `-Wunsafe` is
# almost impossible.
ghc-options:
  "$locals": -Weverything -Werror -Wno-unsafe

system-ghc: true
