resolver: lts-22.15

packages:
  - bin
  - logic
  - logic-core

# Safe Haskell makes things really complicated.
ghc-options:
  "$locals": -Weverything -Werror -Wno-safe -Wno-unsafe -Wno-missing-safe-haskell-mode
  gimlight-logic-core: -w

system-ghc: true
