Require Coq.extraction.Extraction.
Require Coq.extraction.ExtrHaskellBasic.
Require Coq.extraction.ExtrHaskellNatInt.

From Gimlight Require Import Logic.GameModel.

Extraction Language Haskell.

Set Extraction Output Directory "logic-core".
Set Extraction File Comment "This file has been automatically generated by Coq codes in `logic-core`. Do not modify it by hand.".

Extraction "GimlightLogicCore" game_model init_game_model increment get_count.
