module FovSpec
    ( spec
    ) where

import           Data.Array (array)
import           Fov        (calculateFov)
import           Linear.V2  (V2 (V2))
import           Test.Hspec (Spec, describe, it, shouldBe)

spec :: Spec
spec =
    describe "calculateFov" $
    it "calculates FoV from the previous FoV generated by `darkFov` successfully" $
    calculatedFov `shouldBe` expectedFov
  where
    expectedFov =
        array (V2 0 0, V2 2 2) [(V2 x y, True) | x <- [0 .. 2], y <- [0 .. 2]]
    calculatedFov = calculateFov (V2 1 1) transparentMap
    transparentMap =
        array (V2 0 0, V2 2 2) [(V2 x y, True) | x <- [0 .. 2], y <- [0 .. 2]]
