Require Coq.extraction.Extraction.
Require Coq.extraction.ExtrHaskellNatInt.

From Gimlight Require Import GameModel.

Set Extraction Output Directory "src".
Set Extraction File Comment "This file was automatically generated by Coq. Edit Coq files instead!".

Extraction Language Haskell.

Extraction "GimlightLogicCore.hs" Gimlight.GameModel.GameModel init_game_model increment get_count.
