module Gimlight.FovSpec
    ( spec
    ) where

import           Data.Array       (listArray)
import           Gimlight.Fov     (calculateFov)
import           Gimlight.Prelude
import           Linear.V2        (V2 (V2))
import           Test.Hspec       (Spec, describe, it, shouldBe)

spec :: Spec
spec = do
    testFovCalculationOfWidthHeight 3 3
    testFovCalculationOfWidthHeight 2 4

testFovCalculationOfWidthHeight :: Int -> Int -> Spec
testFovCalculationOfWidthHeight mapWidth mapHeight =
    describe "calculateFov" $
    it ("calculates FoV of " <>
        show mapWidth <>
        "x" <>
        show mapHeight <>
        " from the previous FoV generated by `darkFov` successfully") $
    calculatedFov `shouldBe` expectedFov
  where
    expectedFov =
        listArray (V2 0 0, V2 (mapWidth - 1) (mapHeight - 1)) (repeat True)
    calculatedFov = calculateFov playerPosition transparentMap
    transparentMap =
        listArray (V2 0 0, V2 (mapWidth - 1) (mapHeight - 1)) (repeat True)
    playerPosition = V2 1 1
