name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check-if-cabal-file-is-up-to-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      # See https://github.com/commercialhaskell/stack/issues/3697#issuecomment-353729540.
      - name: Check if the cabal file is up to date
        run: |
          mv gimlight.cabal gimlight.cabal.old
          stack build --dry-run
          diff gimlight.cabal.old gimlight.cabal

  disallow-binary:
    runs-on: ubuntu-latest

    steps:
      - name: Check if a file is a binary
        run: |
          binaries=$(git ls-files -z|xargs --null file --dereference --mime|grep 'charset=binary'|cut -d: -f1)
          if [ -n "$binaries" ]; then
            echo "Do not commit the following binary files as git does not handle them well"
            echo "$binaries"
            exit 1
          fi

  hlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install `hlint`
        uses: haskell-actions/hlint-setup@0b0024319753ba0c8b2fa21b7018ed252aed8181 # v2.4.9

      - name: Run `hlint`
        uses: haskell-actions/hlint-run@96199a3357287063c67606b26d533f1acb4b6c4e # v2.4.9
        with:
          path: .
          fail-on: status

  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Run `markdown-lint`
        uses: DavidAnson/markdownlint-cli2-action@510b996878fc0d1a46c8a04ec86b06dbfba09de7 # v15.0.0

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Run `prettier` with the check mode
        run: npx --yes prettier --check .

  stan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install `stan`
        run: cabal install stan --with-compiler=$(stack path --compiler-exe)

      - name: Build the project with HIE
        run: stack build --ghc-options -fwrite-ide-info --ghc-options -hiedir=.hie

      - name: Run `stan`
        run: |
          stan check --exclude --filter-all --scope-all \
               check --include --filter-all --directory=app \
               check --include --filter-all --directory=src \
               check --include --filter-all --directory=test

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install dependencies
        id: haskell-setup
        uses: haskell-actions/setup@ca7ecf7b0c7a4300227b1ab05cda52bf019c174b # v2.0.0
        with:
          enable-stack: true

      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            .stack-root
            ${{ steps.haskell-setup.outputs.stack-root }}
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ github.sha }}
          restore-keys: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}

      - name: Build
        run: stack build

      - name: Run tests
        run: stack test

  trailing-newline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: List all non-empty files tracked by git that do not end with a newline
        run: git ls-files | xargs -I {} sh -c '[ -s "{}" ] && echo "{}"' | xargs -I {} sh -c 'tail -c 1 {} | read -r _ || (echo "{}"; false)'
