name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  disallow-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Check if a file is a binary
        run: |
          binaries=$(git ls-files -z|xargs --null file --dereference --mime|grep 'charset=binary'|cut -d: -f1)
          if [ -n "$binaries" ]; then
            echo "Do not commit the following binary files as git does not handle them well"
            echo "$binaries"
            exit 1
          fi
