name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  disallow-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Check if a file is a binary
        run: |
          binaries=$(git ls-files -z|xargs --null file --dereference --mime|grep 'charset=binary'|cut -d: -f1)
          if [ -n "$binaries" ]; then
            echo "Do not commit the following binary files as git does not handle them well"
            echo "$binaries"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install dependencies
        id: haskell-setup
        uses: haskell-actions/setup@ca7ecf7b0c7a4300227b1ab05cda52bf019c174b # v2.0.0
        with:
          enable-stack: true

      - name: Cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2.0.0
        with:
          path: |
            .stack-root
            ${{ steps.haskell-setup.outputs.stack-root }}
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ github.sha }}
          restore-keys: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}

      - name: Build
        run: stack build

      - name: Run tests
        run: stack test
